### ISSUE TITLE
[flutter web] add support for flutter web

### ISSUE THREAD

**Issue by hmbenhaim** [ertgrulll/advstory#1]
**Add support to the package for flutter web**
Hi, this looks like an amazing package, I'm using a different package for stories, this one look much richer package, I'm working with flutter on the web.

**My suggestion is to remove caching if kIsWeb is true**
I browsed a little bit in the source code of the package and I saw that the only thing that you depend on is the caching which is not currently available for the web, I just wondering if you can add a condition in case id kIsWeb true to get the image from the internet instead of the caching mechanism. 

thank you

**Comment by hmbenhaim** [comment]
Ok I can test it on the web without caching I'll see if I can find a solution for all the rest of the issues that will come up.

**Comment by ertgrulll** [comment]
I've added this to the [roadmap](https://github.com/ertgrulll/advstory#roadmap), I'm closing the issue. You can use [discussions](https://github.com/ertgrulll/advstory/discussions) to discuss or advice anything about this feature.
