### ISSUE TITLE
Update Example Stories & JSON

### ISSUE THREAD

**Issue by jtkeyva** [ertgrulll/advstory#10]
**Is your feature request related to a problem? Please describe.**
No a problem, but something useful was taken from first release.

**Describe the solution you'd like**
The first release had a few different stories and a nice JSON file to see how everything works. Bring back the JSON file. The JSON helped show how to model real world input data and parse it.

Add a couple more different stories so you can see how the JSON should be structured and to get a feel what it's like to advance to the next story when viewing it.

**Describe alternatives you've considered**
Using the data file from the previous release.

**Additional context**
Nested data can get a little tricky so it's nice to see how you consume and parse it into different stories.

**Comment by ertgrulll** [comment]
I changed that to simplify example project, you can check [data_generator.dart](https://github.com/ertgrulll/advstory/blob/8dacb2e143975f8c5b91e0e63f5eb7ef70a834ab/example/lib/data_generator.dart) for json, model is not standard for every project.

**Comment by jtkeyva** [comment]
Ok thanks. I was thinking you could leave it in there for an "advanced real world use case example". I am using Supabase and working on a clean way to build the data. Perhaps I can contribute a Supabase example.

**Comment by ertgrulll** [comment]
I will create additional resources section in [documentation](https://advstory.sourcekod.com). If you want, you can write a medium post or something else. `AdvStory` doesn't appear in Google search results unless you specifically search for it, if you can I would really appreciate it 🙏🏼 In any case, I will add you to the contributors for your efforts in the next release. Also, if you want to contact me about this, you can use Linkedin.

**Comment by jtkeyva** [comment]
got it thanks. still battling with pulling in the data from postgres to populate the tray and stories. once i figure it out then i can try and explain my process
