### ISSUE TITLE
[BUG] Content Skip

### ISSUE THREAD

**Issue by itsjanjan** [ertgrulll/advstory#16]
Suddenly skipped to next content when I open and close the keyboard (3 times in row) without any tapping on the content. I just open the keyboard via TextField and close it using **DONE** action in KB.

I will share screen record below, I hope you can view it...

https://drive.google.com/file/d/1o7zPy_pY-viN1C0qGuiimtpI8yTic1Rm/view?usp=sharing

**Comment by ertgrulll** [comment]
This bug was due to the stopwatch not being reset during pauses and issue fixed in version 0.2.0 . Thanks for your feedback, again 🥇
