### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by aliaktas-tr** [ertgrulll/advstory#18]
Hello Ertugrul.  Is there any way to disable page bouncing when tapped to AdvStoryTray?

**Comment by ertgrulll** [comment]
Hello, if you mean opening animation which is a slide transition there is no way to change that using AdvStory constructor. You can use AdvStory.player to customize animation, this constructor allows story view without tray list, so you need to create a tray list. Look at example project to see basic usage.

**Comment by aliaktas-tr** [comment]
Thank you.
