### ISSUE TITLE
Sync Tray with Stories

### ISSUE THREAD

**Issue by aytunch** [ertgrulll/advstory#22]
<img width="707" alt="Screen Shot 2022-09-27 at 20 11 52" src="https://user-images.githubusercontent.com/6442915/192594374-e42e650c-2ee7-4f16-a4cb-329fd249d070.png">
Let's say the user browsed the stories and quit the story view in the 7th story. We would expect the 7th story item to be positioned in the middle of the tray.
Is this possible?
Btw thanks a lot for this great package and awesome documentation.

**Comment by ertgrulll** [comment]
Makes sense, thanks for the idea and for your nice comments. I will add this feature in the weekend with #21.

**Comment by BlazingFV** [comment]
> Makes sense, thanks for the idea and for your nice comments. I will add this feature in the weekend with #21.

thanks for caring ! can't wait to get the functionality of #21 done because it's such a pain i can't really say enough about the amazing work you've maybe i'll try to help also i'd like to see the approach you're going with ! 
and thanks in advance

**Comment by ertgrulll** [comment]
@aytunch actually it's possible right now, you can check `AdvStory.player` constructor and `AdvStoryPlayerController` from [here](https://github.com/ertgrulll/advstory/blob/master/example/lib/examples/player.dart). You need to create your own tray view, add listener to story controller and change your tray list position on skips. I didn't add docs for interceptor and player constructor. But I will add this as default behaviour,

**Comment by aytunch** [comment]
@ertgrulll is this merged to master? And can we see it implemented in the example project if possible?
Thank you very much
