### ISSUE TITLE
Decouple Tray & Player

### ISSUE THREAD

**Issue by jtkeyva** [ertgrulll/advstory#3]
**Is your feature request related to a problem? Please describe.**
What if you don't want to display a tray? or You only have a single story to play. What do you do?

**Describe the solution you'd like**
Decouple the Tray and the Story Player so that you can simply play a single story without using the tray. Or have a standalone Story Player.

**Describe alternatives you've considered**
Hacking your code

**Additional context**
N/A
Just wanted to thank you again and say great job. Caching works great and skipping slides is flawless!

**Comment by ertgrulll** [comment]
I was actually thinking about this. I can add some methods to show story view without adding tray list to the tree. You're welcome, happy hacks! Also, thanks for your good highlights.

**Comment by jtkeyva** [comment]
That would be awesome! I really think you're onto a special package here. It's a batteries included approach to stories which is great. Even greater if developers can have fine grain control over functionality and presentation.

Although it's gonna take me some time to understand your code, I will do my best to contribute any ideas or code.

Cheers

ps: perhaps some info on how caching works or a clear cache function could be of use

**Comment by ertgrulll** [comment]
This feature takes some time to implement and I'm currently working on another project. I will try to make time for this in the near future, but I would appreciate it if you open a pr for this feature anyway.

Syntax can be `AdvStory.headless()` for without tray list and `AdvStory()` for with trays.
Looks like [animation controllers](https://github.com/ertgrulll/advstory/blob/8dacb2e143975f8c5b91e0e63f5eb7ef70a834ab/lib/src/advstory.dart#L93-L101) should be moved to [cluster widget](https://github.com/ertgrulll/advstory/blob/master/lib/src/view/cluster_view.dart) and tray view should be moved to a separate class. Flow can be started from `AdvStoryController` or from a new controller that extends `AdvStoryController`. Controller has [preloadMediaFile](https://github.com/ertgrulll/advstory/blob/8dacb2e143975f8c5b91e0e63f5eb7ef70a834ab/lib/src/controller/story_controller_impl.dart#L239-L250) method, this can be used to load media file before opening story view.

After adding this feature I (or you) can add _"batteries included"_ to the readme 🎉

**Comment by jtkeyva** [comment]
Got it, I've never done a PR so I'll see what I can do.

Yeah, naming depends on your goals. Other Story packages are limiting because they force you into using a tray. I would consider the tray an add-on module to the core story player. I feel your player is the meat and potatoes of the package that harnesses the power so to me something like:
`AdvStory() ` or `AdvStory.player()` for the Story Player and `AdvStory.tray()` for the tray.

It's your package, I just really appreciate the performance of the player and feel that if things were modular and had some optional add-ons it could be a force to be reckoned with!

**Comment by jtkeyva** [comment]
I think this is beyond me to handle, I will buy you a mega coffee to complete ☕️ 😀

BTW: i suggested advstory to syntacops and it got featured! hopefully your package picks up some new users, fans & contributors!

https://www.youtube.com/watch?v=Drr48OiB91Y

**Comment by jtkeyva** [comment]
Great to hear! Wow, you have been cranking 😮 Can't wait to try it out and contribute 🥳

**Comment by ertgrulll** [comment]
Hello, I decoupled tray list and player in version 0.2.0. Now, you can customize almost anything about story view. You can see usage in [player example](https://github.com/ertgrulll/advstory/blob/master/example/lib/examples/player.dart). Some minor changes in this version may affect your project, please have a look at the [changelog](https://github.com/ertgrulll/advstory/blob/master/CHANGELOG.md#020).

**Comment by jtkeyva** [comment]
Awesome! Thanks for the hard work. Look forward to trying it out :)
