### ISSUE TITLE
WidgetStory AnimationController exception

### ISSUE THREAD

**Issue by jtkeyva** [ertgrulll/advstory#5]
**Is your feature request related to a problem? Please describe.**
There is no problem, only opportunity. 
The widget type is limitless which is great, but what if you want different widget types for say "Image with text" or "3 image rows" or "Video with scrolling text" or "Video with image overlay"?

**Describe the solution you'd like**
Allow devs to define custom content types with templates. Could be as simple as placing dart files within a content_type or content_template folder: `image_with_text.dart`, `three_image_rows.dart`, `video_with_scrolling_text.dart` or `video_with_image_overlay.dart`

The syntax in the template file could look something like:
`ContentTypeVideoWithScrollingText`
or
`ContentType.videoWithScrollingText`
or
`SlideTemplateVideoWithScrollingText`
or
`SlideTemplate.videoWithScrollingText`

Then in the "cluster" json that populates the stories, you could simply specify what content type / content template will be used for each individual slide. ex `ImageWithTextSlide`, `VideoWithScrollingTextSlide`, `MyCustomTemplateSlide` or `ContentType.myCustomTemplate` or `Slide.myNewSlideTemplate` along with your built in `ImageSlide` `VideoSlide` `WidgetContent`.

```
`ContentType: 'VideoWithScrollingText' {
videoUrl: 'https://mysite.com/linktovideo.mp4'
scrollingText: 'this is the text i want to scroll'
}
`
```
or 

```
`SlideType: 'ImageWithText' {
videoUrl: 'https://mysite.com/linktovideo.mp4'
scrollingText: 'this is the text i want to scroll'
}
`
```

or

```
`Template: 'Advertisement' {
videoUrl: 'https://mysite.com/linktovideo.mp4'
Text: 'Order Now!'
link: 'https://mylink.com/ordernow'
backgroundImageUrl: 'https://mysite.com/bgimage.png'
}
`
```

**Describe alternatives you've considered**
Hacking and breaking your code

**Additional context**
Your story player outperforms all other packages I've tried. I appreciate your built in functionality and your opinionated approach as is. I think if you break it up a bit and modularize it a bit, it could become one of the more powerful packages for content display, particularly in this full screen story format. Not sure of your goals with this package though.

Not sure how much I can help with code, I'm not an expert. I've never done a PR and still wrapping my head around your code. I can do product development and map things out no problem, but implementing them into your code might be tough.

I can do a $ bounty to get this implemented with the other features if it can become a priority.

**Comment by jtkeyva** [comment]
I may be overthinking it. I think the way you are doing custom Header & Footer is super powerful and could be the key. What if you were also able to supply a "Body"/ Main/Template ? I think that's the ticket. So then you can supply a different "Body"/Main/Template based on different developer defined ContentTypes.

Then it's up to the developer to create the logic of what "Template" to show based on what ContentType is in the JSON.

**Comment by jtkeyva** [comment]
Wanted to note there's a foregroundBuilder option in this package:
https://pub.dev/packages/wechat_camera_picker

`typedef ForegroundBuilder = Widget Function(
  BuildContext context,
  CameraValue cameraValue,
);`

Figure you can use some ideas from there?

**Comment by ertgrulll** [comment]
Hi, thanks for your feedback. WidgetStory throws an error when first item in story view, I can reproduce issue. I will release a new version today to fix this issue.
<hr />

> Naming it ContentType (like Drupal does) might be more universal instead of MediaType since there can be several different types of media within a piece of content.

`MediaType` is from example project, i created this enum for generating mock data for showcase, it's not about the package itself. You can use any name inside of your project. Although, I'll rename the enum to avoid confusion.
<hr />

> `typedef ForegroundBuilder = Widget Function( BuildContext context, CameraValue cameraValue, );`

How will it be useful in this package? You can use WidgetStory if it's about using custom widgets over the image or video media. I will add a way to use cached media inside WidgetStory in next releases, this way you don't have to create your own caching mechanism for custom story types.

<hr/>

> I can do a $ bounty to get this implemented with the other features if it can become a priority.
> PPS: Great job again, this really is an awesome package!

I'm grateful for your all kind of supports, I will add _be a sponsor_ or _buy me a coffee_ button to the readme 🙏🏼
