### ISSUE TITLE
Web / MacOS / Windows / Linux Support

### ISSUE THREAD

**Issue by jtkeyva** [ertgrulll/advstory#6]
**Is your feature request related to a problem? Please describe.**
Says it works for iOS & Android

**Describe the solution you'd like**
To work across other platforms

**Describe alternatives you've considered**
None

**Additional context**
Is there anything specific that will make it difficult? I know video, caching & performance can be problematic so not sure how realistic it is.

**Comment by ertgrulll** [comment]
I plan to support more platforms in the long term, it's pretty realistic. The main issue is the cache for other platforms. If I remove caching, performance drops significantly. Story view can be changed on wide screens just like instagram web. After complete other features i'm gonna work on this, I'll work on it after I complete the other features, I've added this to the [roadmap](https://github.com/ertgrulll/advstory#roadmap), I'm closing the issue. You can use [discussions](https://github.com/ertgrulll/advstory/discussions) to discuss this with me or anyone else interested in this feature.

Happy coding!

**Comment by jtkeyva** [comment]
Awesome! I think your option to (conditionally) disable caching is a step in the right direction.
